name: radar-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - boto3
  - requests
  - dask
  - matplotlib
  - numpy
  - pip
  - pyyaml
  - scipy
  - tqdm
  - zarr
  - pytorch
  - torchvision
